# Generated by Django 5.2.8 on 2025-11-19 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IniciacaoCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('area_pesquisa', models.CharField(max_length=200)),
                ('duracao', models.CharField(max_length=100)),
                ('numero_vagas', models.IntegerField()),
                ('descricao', models.TextField()),
                ('bolsa_disponivel', models.BooleanField(default=False)),
                ('tipo_bolsa', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.CharField(max_length=300)),
                ('objetivos', models.TextField(blank=True, null=True)),
                ('requisitos', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(limit_choices_to={'role': 'professor'}, on_delete=django.db.models.deletion.CASCADE, related_name='iniciacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
