# Generated by Django 5.2.8 on 2025-11-20 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresseIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'role': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='interesses', to=settings.AUTH_USER_MODEL)),
                ('iniciacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interessados', to='projects.iniciacaocientifica')),
            ],
            options={
                'unique_together': {('aluno', 'iniciacao')},
            },
        ),
    ]
