# Generated by Django 4.2.26 on 2025-11-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_interesseic'),
        ('projects', '0002_message'),
    ]

    operations = [
    ]
