# Generated by Django 5.2.8 on 2025-11-22 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_merge_0002_interesseic_0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='atualizado_em',
        ),
    ]
