# Generated by Django 5.2.8 on 2025-11-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_message_atualizado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='iniciacaocientifica',
            name='valor_bolsa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
