# Generated by Django 5.2.8 on 2025-11-24 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_areas_pesquisa_customuser_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Já existe um usuário com este nome.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='O nome de usuário deve conter apenas letras, acentos e espaços.', regex='^[A-Za-zÀ-ÖØ-öø-ÿ ]+$')]),
        ),
    ]
