# Generated by Django 5.2.8 on 2025-11-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
